name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          npm ci
          npm run build
        name: Build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-v${{ matrix.node-version }}-release
          path: |
            build
            package.json

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v3
      - name: Zip artifact for deployment
        run: |
          zip node-v16.x-release.zip ./node-v16.x-release/* -r
          zip node-v17.x-release.zip ./node-v17.x-release/* -r
          zip node-v18.x-release.zip ./node-v18.x-release/* -r
          zip node-v19.x-release.zip ./node-v19.x-release/* -r
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
