name: Create Release

on:
  push:
    tags:
      - "v*"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          npm ci
          npm run build
        name: Build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-v${{ matrix.node-version }}-release
          path: |
            build
            prisma
            package-lock.json
            package.json

  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - run: npm run build
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Zip artifact for deployment
        run: |
          (cd node-v16.x-release && zip -r "$OLDPWD/node-v16.x-release.zip" .)
          (cd node-v17.x-release && zip -r "$OLDPWD/node-v17.x-release.zip" .)
          (cd node-v18.x-release && zip -r "$OLDPWD/node-v18.x-release.zip" .)
          (cd node-v19.x-release && zip -r "$OLDPWD/node-v19.x-release.zip" .)
          (cd node-v20.x-release && zip -r "$OLDPWD/node-v20.x-release.zip" .)
          (cd node-v21.x-release && zip -r "$OLDPWD/node-v21.x-release.zip" .)
      - name: Create Release
        run: gh release create ${{github.ref_name}} --generate-notes ./*.zip
